### ISSUE TITLE
Issue sending message after initiating conversation

### ISSUE THREAD

**Issue by LAnders0n** [RTippin/messenger#50]
After initiating a conversation and creating a thread, when trying to send a message on the same thread, getting the following as the response: "Not authorized to send messages."
If you could provide a demo of the API and payload, it will be helpful

Thank you.

**Comment by RTippin** [comment]
@LAnders0n  When you send messages, are you getting the unauthorized response from sending messages as the recipient, or from the provider that initially started the thread? It could be that you have the [private_thread_friendship](https://github.com/RTippin/messenger/blob/1.x/config/messenger.php#L265) flag enabled, thus the thread would be "pending" for the recipient if they were not already friends with the sender, and unable to send messages unless they approved the pending thread.

Demo wise, I already have up https://tippindev.com/ as well as the repo for it, https://github.com/RTippin/messenger-demo

Hope this helps.

**Comment by LAnders0n** [comment]
Sending from the provider that initially started the thread. The [private_thread_friendship] is not enabled. Also, this link does not work, https://tippindev.com/. It would be really helpful if you could provide an example of the APIs and the payloads.

**Comment by ajnozari** [comment]
> Sending from the provider that initially started the thread. The [private_thread_friendship] is not enabled. Also, this link does not work, https://tippindev.com/. It would be really helpful if you could provide an example of the APIs and the payloads.

An API a explorer is linked in the readme 

[Api Explorer](https://tippindev.com/api-explorer)

**Comment by RTippin** [comment]
@LAnders0n If my demo site isn't working for you, then clone my demo repo, follow the install steps, and you will have my demo site, api explorer and all, on your own machine. 

As per your issue with being unauthorized, I'm afraid I can't help you without more context.

**Comment by LAnders0n** [comment]
![Screenshot (574)](https://user-images.githubusercontent.com/114661260/193573412-f0dfa5f1-362a-48cb-aaf1-378ea183aa90.png)
![Screenshot (575)](https://user-images.githubusercontent.com/114661260/193573420-91026015-a778-4e9e-a9bd-9b27f7cafcb6.png)

This is the error I'm facing.

My code looks like this (messages.php)
    'thread_verifications' => [
        'private_thread_friendship' => false,
        'group_thread_friendship' => env('MESSENGER_VERIFY_GROUP_THREAD_FRIENDSHIP', false),
    ],
    
 Could you please point out where I'm making a mistake?

**Comment by RTippin** [comment]
@LAnders0n any chance you could make your code/repo public? Only asking as it would be faster for me to cross check the areas it might be. Based on your screenshot, everything seems correct, so it could be the user/provider you are authenticated as. Just double checking, you have your user/provider models registered with messenger inside the messenger service provider or your own?

**Comment by LAnders0n** [comment]
I'm afraid I can't make it public. I think I know what's causing the issue. The user/provider I'm authenticated as is showing null when I try to access the facade from the package but shows the data when I do the same from other controllers. So I'm guessing that the package is not correctly configured with my auth. I have double-checked the steps but am still not able to figure it out. Could you please help me from here?

**Comment by RTippin** [comment]
@LAnders0n Odd you would be getting an authorization error and not an authentication error, especially because to get that policy error message, you would have to pass my default middleware that sets the messenger provider for the request. 

> https://github.com/RTippin/messenger/blob/1.x/config/messenger.php#L81
> https://github.com/RTippin/messenger/blob/1.x/src/Http/Middleware/SetMessengerProvider.php

What type of authentication are you using, and did you update my routing middleware to reflect that? You do not have to use my included middleware, but what is important is that a middleware sets my "provider" before going to any of my controllers. 

```
Messenger::setProvider($user);
```

**Comment by RTippin** [comment]
@LAnders0n Any updates on your issue? If not, please mark this as closed.

**Comment by LAnders0n** [comment]
Thanks for the help
Closing the issue now

**Comment by GMT95** [comment]
If anyone comes across this issue, they might have a problem with Laravel's `SubstituteBindings` middleware not being called. In my case, I am using this package as API only.

When I added a message in a thread using this API:

`POST: api/messenger/threads/{thread}/messages`

the thread model was not retrieved. I was getting:

`403 "message": "Not authorized to send messages."`

In my case, the user I was calling the API from was a participant of the group and had permission to send messages. The error was that the `MessagePolicy`'s `create` method was returning an access denied response. This policy checks for the thread ID, owner ID, and owner type in the participants table, but the thread ID was `null` because `SubstituteBindings` was not called.

### How I fixed it:

In `config/messenger.php`, I updated the `middleware` array in the `'api'` group.

**Solution 1: Add the `api` middleware**

By adding the `'api'` middleware, the middleware group calls `SubstituteBindings` automatically.

```php
'api' => [
    'domain' => null,
    'prefix' => 'api/messenger',
    'middleware' => ['api', 'auth:api', 'messenger.provider:required'], // add `api` middleware
    'invite_api_middleware' => ['web', 'messenger.provider'],
],
```

**Solution 2: Directly add the `bindings` middleware**

You can directly add the `bindings` middleware without using the `'api'` group. This requires that `'bindings'` is already mapped to the `SubstituteBindings` class in `Http/Kernel.php`'s `$middlewareAliases` array.

```php
'api' => [
    'domain' => null,
    'prefix' => 'api/messenger',
    'middleware' => ['auth:api', 'messenger.provider:required', 'bindings'], // add `bindings` middleware
    'invite_api_middleware' => ['web', 'messenger.provider'],
],
```

There might be same problem with: #58
